[package]
name = "dtrd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bp7 = {path = "../bp7"}
tcpcl = {path = "../tcpcl"}
log = "0.4"
tonic = "0.5.2"
prost = "0.8"
tokio = { version = "1.10.0", features = ["full"] }
tokio-stream = "0.1.7"
tokio-util = "0.6.8"
futures-util = "0.3.16"
env_logger = "0.8.4"
async-trait = "0.1.51"

[build-dependencies]
tonic-build = "0.5.2"