[package]
name = "replistore"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
log = "0.4"
env_logger = "0.10.0"
prost = "0.12.1"
dtrd_client = {path = "../client"}
tokio = { version = "1.33.0", features = ["full"] }
futures-util = "0.3.28"
s3s = "0.8.0"
hyper = "0.14.27"
anyhow = "1.0.75"
async-trait = "0.1.74"
tokio-util = { version = "0.7.10", features = ["full"] }
bytes = "1.5.0"
time = "0.3.30"

[build-dependencies]
prost-build = { version = "0.12.1" }
