[package]
name = "tcpcl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
tokio = { version = "1.10.0", features = ["io-util", "net", "macros", "sync", "time"] }
log = "0.4"
env_logger = "0.8.4"
num_enum = "0.5.4"