[package]
name = "tcpcl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
tokio = { version = "1.10.0", features = ["full"] }
log = "0.4"
env_logger = "0.8.4"
num_enum = "0.5.4"

[[bin]]
name="server"
path = "bin/server.rs"

[[bin]]
name="client"
path = "bin/client.rs"