# Copyright (C) 2023 Felix Huettner
#
# This file is part of DTRD.
#
# DTRD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DTRD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: license

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  license:

    name: Check License
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v5

      - name: Check License Header
        uses: apache/skywalking-eyes/header@main
        # with:
            # log: debug # optional: set the log level. The default value is `info`.
            # config: .licenserc.yaml # optional: set the config file. The default value is `.licenserc.yaml`.
            # token: # optional: the token that license eye uses when it needs to comment on the pull request. Set to empty ("") to disable commenting on pull request. The default value is ${{ github.token }}
            # mode: # optional: Which mode License-Eye should be run in. Choices are `check` or `fix`. The default value is `check`.